doctrine:
    dbal:
        types:
            vehicle_chassis: 'Muffler\Vehicle\Infrastructure\Persistence\Doctrine\DBAL\Types\ChassisType'
    orm:
        mappings:
            Vehicle:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Vehicle/Domain/Entity'
                prefix: 'Muffler\Vehicle\Domain\Entity'
                alias: Vehicle
